### ISSUE TITLE
invalid memory address or nil pointer dereference signal SIGSEGV

### ISSUE THREAD

**Issue by richb-hanover** [network-quality/goresponsiveness#11]
* I attempted to use `docker run goresp` on the Docker image built a couple days ago on my MacBook Pro (same machine that built the image) and got the error message below. It happened two times in succession. (That Docker image had worked for dozens of times previously.)

* I then ran the go code on macOS with `./networkQuality --config mensura.cdn-apple.com --port 443 --path /api/v1/gm/config --debug` and the program ran successfully producing believable results.

* I rebuilt the Docker container with `docker build -t goresp .` It appears that process re-downloaded a big (110 mbyte) file, but the build completed without incident. I did _not_ retrieve new code for networkQuality.go - `git log` shows my machine has commit 710fb3cb8bc32eb1250f333b8184ba044f627ad5
 
* I then re-ran `docker run goresp` and got reasonable, believable results from the Docker image several times in a row

So - not reproducible, but perhaps you can get some hints from the stack trace. ("We promise not to fix it if we don't know it's happening..." :-)

```
03-23-2022 23:29:33 UTC Go Responsiveness to mensura.cdn-apple.com:443...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x62d367]

goroutine 196 [running]:
github.com/network-quality/goresponsiveness/ccw.(*ConcurrentWriter).Write(0x6c9d42, {0xc0002b0bb0, 0xa2, 0x3})
	/goresponsiveness/ccw/ccw.go:18 +0x47
crypto/tls.(*Config).writeKeyLog(0xc0004f3c80, {0x6d1d64, 0xc0000f88c0}, {0xc0000f8080, 0x20, 0x20}, {0xc0000f87e0, 0x20, 0x20})
	/usr/local/go/src/crypto/tls/common.go:1317 +0x1b9
crypto/tls.(*clientHandshakeStateTLS13).establishHandshakeKeys(0xc0004499b8)
	/usr/local/go/src/crypto/tls/handshake_client_tls13.go:367 +0x28d
crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc0004499b8)
	/usr/local/go/src/crypto/tls/handshake_client_tls13.go:81 +0x1b3
crypto/tls.(*Conn).clientHandshake(0xc00057e380, {0x730738, 0xc000115380})
	/usr/local/go/src/crypto/tls/handshake_client.go:219 +0x585
crypto/tls.(*Conn).handshakeContext(0xc00057e380, {0x730770, 0xc00009a000})
	/usr/local/go/src/crypto/tls/conn.go:1445 +0x3d1
crypto/tls.(*Conn).HandshakeContext(...)
	/usr/local/go/src/crypto/tls/conn.go:1395
crypto/tls.dial({0x730770, 0xc00009a000}, 0xc0002134a0, {0x6c8d3e, 0x3}, {0xc0001a8000, 0x19}, 0xc0004f3c80)
	/usr/local/go/src/crypto/tls/tls.go:157 +0x3b1
crypto/tls.(*Dialer).DialContext(0x8, {0x730770, 0xc00009a000}, {0x6c8d3e, 0x2}, {0xc0001a8000, 0x10000000055b559})
	/usr/local/go/src/crypto/tls/tls.go:217 +0x8d
golang.org/x/net/http2.(*Transport).dialTLSWithContext(0x203000, {0x730770, 0xc00009a000}, {0x6c8d3e, 0x0}, {0xc0001a8000, 0xc0000982d0}, 0x0)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/go115.go:21 +0x4d
golang.org/x/net/http2.(*Transport).dialTLS.func1({0x6c8d3e, 0xc0001a8000}, {0xc0001a8000, 0xc0000982d0}, 0x2d)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/transport.go:620 +0x65
golang.org/x/net/http2.(*Transport).dialClientConn(0x6f6c44360a59536a, {0x730770, 0xc00009a000}, {0xc0001a8000, 0x19}, 0x60)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/transport.go:594 +0xb2
golang.org/x/net/http2.(*dialCall).dial(0xc00058b280, {0x730770, 0xc00009a000}, {0xc0001a8000, 0x19})
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/client_conn_pool.go:141 +0x45
created by golang.org/x/net/http2.(*clientConnPool).getStartDialLocked
	/go/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/client_conn_pool.go:134 +0x1f3
%
```

**Comment by hawkinsw** [comment]
Very interesting report! Thank you! I will definitely dig in to this and see what is causing it. Thanks again for all the work and contributions! I really appreciate it!

Will
